
// --- Game Config ---
export const GAME_DURATION = 20; // in seconds

// --- Word List ---
export const WORD_LIST = [
    "html",
    "css",
    "typescript",
    "json",
    "node",
    "api",
    "endpoint",
    "requisição http",
    "sql",
    "postgresql",
    "neon database",
    "query",
    "modelagem de dados",
    "diagrama er",
    "uml",
    "orientação a objetos",
    "classe",
    "instância",
    "herança",
    "polimorfismo",
    "interface",
    "terminal",
    "linha de comando",
    "linux",
    "sistema operacional",
    "ide",
    "vs code",
    "intellij",
    "flask",
    "fastapi",
    "spring boot",
    "arquitetura mvc",
    "microserviço",
    "api gateway",
    "autenticação jwt",
    "login",
    "middleware",
    "deploy automático",
    "github actions",
    "versionamento",
    "merge conflict",
    "commit bugado",
    "rollback",
    "frontend quebrado",
    "responsividade",
    "tailwind",
    "bootstrap",
    "firebase",
    "cloud computing",
    "docker",
    "kubernetes",
    "virtual machine",
    "inteligencia de dados",
    "ci cd",
    "debug mode",
    "stack overflow",
    "projeto tcc",
    "scrum",
    "kanban",
    "sprint",
    "documentação técnica",
    "testes unitários",
    "api pública",
    "variável global",
    "função assíncrona",
    "callback",
    "promessa rejeitada",
    "console.log",
    "print",
    "erro 404",
    "servidor offline",
    "deploy falhou",
    "commit de sexta-feira",
    "codigo spaghetti",
    "refatoração",
    "clean code",
    "design pattern",
    "dev fullstack",
    "backend raiz",
    "frontend nutella",
    "deploy nervoso",
    "bug misterioso",
    "devops",
    "computação em nuvem",
    "ciência de dados",
    "engenharia de dados",
    "inteligência computacional",
    "iot",
    "arduino",
    "esp32",
    "sensores",
    "algoritmo genético",
    "rede neural",
    "tcc finalizado",
    "frontend",
    "backend",
    "deploy",
    "fullstack",
    "banco de dados",
    "inteligencia artificial",
    "machine learning",
    "debug",
    "commit",
    "javascript",
    "framework",
    "biblioteca",
    "algoritmo",
    "api rest",
    "servidor local",
    "git push",
    "dockerizar",
    "react",
    "componente",
    "renderizar",
    "estado",
    "python",
    "compilador",
    "engenharia de software",
    "documentação",
    "formatura tech",
    "projeto integrador"
];


// --- Surprise Message ---
export const SURPRISE_MESSAGE_PARTS = [
    "Atenção, Atenção,",
    "João e Rafael,",
    "vocês estão sendo convocados para serem,",
    "nossos padrinhos de formatura!!",
    "Vocês aceitam essa missão??"
];
